require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false

  Exclude:
    - "db/schema.rb"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "db/migrate/*"
    - "db/seeds.rb"
    - "**/*.txt"
    - "**/.keep"
    - "spec/rails_helper.rb"
    - "vendor/**/*"
    - "Rakefile"

  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false